---
version: "2"

services:

  # --- PHP 7.3
  php:
    container_name: "devlorem-php"
    image: bitnami/php-fpm:7.3-prod
    volumes:
      - .:/app

  # --- nginx 1.14
  nginx:
    container_name: "devlorem-nginx"
    image: bitnami/nginx:1.14
    ports:
      - "80:8085"
    depends_on:
      - php
    volumes:
      - .:/app
      - ./docker/nginx.conf:/opt/bitnami/nginx/conf/vhosts/site.conf:ro
