name: Test with Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
      - name: Install required packages
        run: |
          go get github.com/gorilla/mux
          go get github.com/spf13/cobra
      - name: Link main repo as package
        run: |
          mkdir /home/runner/go/src/github.com/Kovah
          ln -s /home/runner/work/DevLorem/DevLorem /home/runner/go/src/github.com/Kovah/DevLorem
      - name: Build and test with Go
        run: |
          go test github.com/Kovah/DevLorem/helper
          go test github.com/Kovah/DevLorem/sources
